### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by dirkjf** [DamienHarper/doctrine-audit-bundle-demo#2]
Reading about this audit bundle and looking at the screenshots, it looks really useful. This demo though, seems a bit incomplete to me. There are no controllers, no forms and only the base template. Am I missing something?

**Comment by DamienHarper** [comment]
@dirkjf the demo is a simple (empty) symfony application with a few entities and fixtures to populate the relevant tables as well as audit tables.
All the logic is embedded in the bundle (controllers and templates)
It allows to demonstrate how the bundle works and how the included templates look like.
You still can experiment and override templates in this demo app if you wish.
What else would you expect?

**Comment by dirkjf** [comment]
I had hoped for a demo that I could simply clone, install dependencies and then run to see how the bundle works. By default (unless I am missing something?) there are no CRUD operations in this code so I cannot test to see how things work, although you write "It allows to demonstrate how the bundle works and how the included templates look like." I don't see how without first writing some CRUD control for the entities, right?

**Comment by dirkjf** [comment]
Sorry, I did not realize I could just go to /audit to see the demo!
